### ISSUE TITLE
"How to Edit Menu" in openbox's menu.xml must go

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-configs#21]
I'm not a native speaker of the English language so I would like to ask around before committing any changes: Does the "How to Edit Menu" entry in the openbox main menu sound like bad English just to my German ears?

Because I would totally change that into something else, or rather, I would like to remove it altogether since it feels kinda out-of-place. Maybe this should be hidden away in a 'Docs' or 'Documentation' submenu, together with other bunsen-docs stuff.

**Comment by capn-damo** [comment]
"How to Edit the Menu" is more correct, but is a bit long imo.

My idea was to reduce the number of "How do I edit the menu?" questions on the forums, and is directed at new users. Since there are now a lot of pipemenus, there is also a section in the doc specifically for those questions.

Move it to the Help submenu? 

Those who know how to edit the menu already can remove it easily enough.

**Comment by johnraff** [comment]
Compromise: move it to Settings>Openbox at the bottom, after the menu-editing options? That would be consistent with some other submenus that have a _help_ or _man_ item at the bottom.

**Comment by ghost** [comment]
@johnraff I would favour moving the thing since as @capn-damo says, the menu would grow too wide with the fixed label.

**Comment by capn-damo** [comment]
How does this look?

![scrot-menu](https://cloud.githubusercontent.com/assets/11060704/7890990/95b004e6-0641-11e5-9aa7-0dfee877cfc2.jpg)

**Comment by johnraff** [comment]
Looks good to me. @2ion ?

**Comment by ghost** [comment]
Looks good!

**Comment by capn-damo** [comment]
Add to Changelog?:

`Moved 'How to Edit Menu' item to 'Settings/Openbox' in menu.xml`

**Comment by johnraff** [comment]
Done. Thanks.
