### ISSUE TITLE
Why are the remaining bl-* scripts not in bunsen-utilities?

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-configs#28]
For clean namespace separation purposes.

**Comment by johnraff** [comment]
Short answer: modularity

---

The bl-\* scripts in bunsen-utilities, although mostly called by internal things like pipemenus, are also intended to be available to a user who might want to use them for some reason. They are installed to /usr/bin (Actually, IMHO there might be a case, on the basis of the reasons below, for moving some of them to bunsen-pipemenus.)

While bl-alternatives and bl-gvim in bunsen-configs also install to /usr/bin, and are available to the user, they are _essential_ for the correct working of the bl alternatives system, which is set up by bunsen-configs. That also adds a dpkg hook, installs .desktop files in /usr/share/applications, and uses references to eg _bl-text-editor_ throughout the config files in skel.

bl-user-setup in bunsen-configs is installed to /usr/lib/bunsen/bunsen-configs and should _only_ be called by lightdm, due to a setting in lightdm.conf, also installed by bunsen-configs.

So on the principle of not calling things in a package which are not provided by that package, or supplied by the system, I chose to put the necessary scripts in bunsen-configs. If they had gone in bunsen-utilities then that would need to be a hard dependency of bunsen-configs. 

The aim was to make it as easy as possible for a user with special needs to install only a subset of packages from the BunsenLabs set without breaking too much. (Of course a certain level of inconvenience might be unavoidable.)

The whole topic of inter-package dependencies and the distribution of files between packages is, however, still open to discussion, and I'm ready to be convinced a different arrangement might be better.

**Comment by ghost** [comment]
OK. I was just asking because I was writing package content descriptions for the website and wondered whether I should remark the script content in -configs.

I do find the dependency configs -> utilities appropriate however. I'm in favour of moving the scripts to there. It's however a non-issue for me if the move doesn't happen.

**Comment by johnraff** [comment]
At the moment bunsen-configs
"Recommends: bunsen-utilities"
so without b-u some functionality would be broken but the b-c package still remains useful.

However, if bl-user-setup is missing lightdm login becomes impossible. This is obviously unacceptable, so the choice is between a hard dependency on b-u and including bl-user-setup in bunsen-configs.

If bl-alternatives is missing the consequences are less severe: /etc/apt/apt.conf.d/90bunsen sets a dpkg hook, but if the file is missing things continue anyway, just without updating the BL alternatives. 

I still feel that it's best to try and minimize possible issues with _system-related_ stuff (being run by root) as opposed to userland scripts, and package the related files together - if you're OK with that in this case?
